// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package taotao.grpcbe;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Greeting.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
