// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package taotao.grpcbe;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Greeting.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
